// Generated by scripts/export_politics_candidate_slots.mjs from web/static/data/v1/politics-static.json.
// Do not edit this file by hand.

import type { PoliticsCandidateSlotCatalog } from '$lib/scenario/politics-candidate-slots';

type UninominalSlotTuple = [string, string, string, string, string, string, string];
type PlurinominalSlotTuple = [string, string, string, string, string, number, number];

const uninominalRows: UninominalSlotTuple[] = [
  [
    "camera",
    "101",
    "Piemonte 1",
    "10101",
    "Piemonte 1 - P01",
    "10101",
    "Piemonte 1 - U01"
  ],
  [
    "camera",
    "101",
    "Piemonte 1",
    "10101",
    "Piemonte 1 - P01",
    "10102",
    "Piemonte 1 - U02"
  ],
  [
    "camera",
    "101",
    "Piemonte 1",
    "10101",
    "Piemonte 1 - P01",
    "10103",
    "Piemonte 1 - U03"
  ],
  [
    "camera",
    "101",
    "Piemonte 1",
    "10102",
    "Piemonte 1 - P02",
    "10104",
    "Piemonte 1 - U04"
  ],
  [
    "camera",
    "101",
    "Piemonte 1",
    "10102",
    "Piemonte 1 - P02",
    "10105",
    "Piemonte 1 - U05"
  ],
  [
    "camera",
    "102",
    "Piemonte 2",
    "10201",
    "Piemonte 2 - P01",
    "10202",
    "Piemonte 2 - U02"
  ],
  [
    "camera",
    "102",
    "Piemonte 2",
    "10201",
    "Piemonte 2 - P01",
    "10203",
    "Piemonte 2 - U03"
  ],
  [
    "camera",
    "102",
    "Piemonte 2",
    "10202",
    "Piemonte 2 - P02",
    "10201",
    "Piemonte 2 - U01"
  ],
  [
    "camera",
    "102",
    "Piemonte 2",
    "10202",
    "Piemonte 2 - P02",
    "10204",
    "Piemonte 2 - U04"
  ],
  [
    "camera",
    "102",
    "Piemonte 2",
    "10202",
    "Piemonte 2 - P02",
    "10205",
    "Piemonte 2 - U05"
  ],
  [
    "camera",
    "201",
    "Valle d'Aosta/Vall\u00e9e d'Aoste",
    "",
    "",
    "20001",
    "Valle d'aosta/Vall\u00e9e d'Aoste - U01"
  ],
  [
    "camera",
    "301",
    "Lombardia 1",
    "30101",
    "Lombardia 1 - P01",
    "30104",
    "Lombardia 1 - U04"
  ],
  [
    "camera",
    "301",
    "Lombardia 1",
    "30101",
    "Lombardia 1 - P01",
    "30105",
    "Lombardia 1 - U05"
  ],
  [
    "camera",
    "301",
    "Lombardia 1",
    "30101",
    "Lombardia 1 - P01",
    "30107",
    "Lombardia 1 - U07"
  ],
  [
    "camera",
    "301",
    "Lombardia 1",
    "30101",
    "Lombardia 1 - P01",
    "30108",
    "Lombardia 1 - U08"
  ],
  [
    "camera",
    "301",
    "Lombardia 1",
    "30101",
    "Lombardia 1 - P01",
    "30109",
    "Lombardia 1 - U09"
  ],
  [
    "camera",
    "301",
    "Lombardia 1",
    "30102",
    "Lombardia 1 - P02",
    "30101",
    "Lombardia 1 - U01"
  ],
  [
    "camera",
    "301",
    "Lombardia 1",
    "30102",
    "Lombardia 1 - P02",
    "30102",
    "Lombardia 1 - U02"
  ],
  [
    "camera",
    "301",
    "Lombardia 1",
    "30102",
    "Lombardia 1 - P02",
    "30103",
    "Lombardia 1 - U03"
  ],
  [
    "camera",
    "301",
    "Lombardia 1",
    "30102",
    "Lombardia 1 - P02",
    "30106",
    "Lombardia 1 - U06"
  ],
  [
    "camera",
    "302",
    "Lombardia 2",
    "30201",
    "Lombardia 2 - P01",
    "30201",
    "Lombardia 2 - U01"
  ],
  [
    "camera",
    "302",
    "Lombardia 2",
    "30201",
    "Lombardia 2 - P01",
    "30202",
    "Lombardia 2 - U02"
  ],
  [
    "camera",
    "302",
    "Lombardia 2",
    "30202",
    "Lombardia 2 - P02",
    "30203",
    "Lombardia 2 - U03"
  ],
  [
    "camera",
    "302",
    "Lombardia 2",
    "30202",
    "Lombardia 2 - P02",
    "30204",
    "Lombardia 2 - U04"
  ],
  [
    "camera",
    "302",
    "Lombardia 2",
    "30202",
    "Lombardia 2 - P02",
    "30205",
    "Lombardia 2 - U05"
  ],
  [
    "camera",
    "303",
    "Lombardia 3",
    "30301",
    "Lombardia 3 - P01",
    "30301",
    "Lombardia 3 - U01"
  ],
  [
    "camera",
    "303",
    "Lombardia 3",
    "30301",
    "Lombardia 3 - P01",
    "30302",
    "Lombardia 3 - U02"
  ],
  [
    "camera",
    "303",
    "Lombardia 3",
    "30302",
    "Lombardia 3 - P02",
    "30303",
    "Lombardia 3 - U03"
  ],
  [
    "camera",
    "303",
    "Lombardia 3",
    "30302",
    "Lombardia 3 - P02",
    "30304",
    "Lombardia 3 - U04"
  ],
  [
    "camera",
    "303",
    "Lombardia 3",
    "30302",
    "Lombardia 3 - P02",
    "30305",
    "Lombardia 3 - U05"
  ],
  [
    "camera",
    "304",
    "Lombardia 4",
    "30401",
    "Lombardia 4 - P01",
    "30401",
    "Lombardia 4 - U01"
  ],
  [
    "camera",
    "304",
    "Lombardia 4",
    "30401",
    "Lombardia 4 - P01",
    "30402",
    "Lombardia 4 - U02"
  ],
  [
    "camera",
    "304",
    "Lombardia 4",
    "30401",
    "Lombardia 4 - P01",
    "30403",
    "Lombardia 4 - U03"
  ],
  [
    "camera",
    "304",
    "Lombardia 4",
    "30401",
    "Lombardia 4 - P01",
    "30404",
    "Lombardia 4 - U04"
  ],
  [
    "camera",
    "401",
    "Trentino-Alto Adige/S\u00fcdtirol",
    "40001",
    "Trentino-Alto Adige/S\u00fcdtirol - P01",
    "40001",
    "Trentino-Alto Adige/S\u00fcdtirol - U01"
  ],
  [
    "camera",
    "401",
    "Trentino-Alto Adige/S\u00fcdtirol",
    "40001",
    "Trentino-Alto Adige/S\u00fcdtirol - P01",
    "40002",
    "Trentino-Alto Adige/S\u00fcdtirol - U02"
  ],
  [
    "camera",
    "401",
    "Trentino-Alto Adige/S\u00fcdtirol",
    "40001",
    "Trentino-Alto Adige/S\u00fcdtirol - P01",
    "40003",
    "Trentino-Alto Adige/S\u00fcdtirol - U03"
  ],
  [
    "camera",
    "401",
    "Trentino-Alto Adige/S\u00fcdtirol",
    "40001",
    "Trentino-Alto Adige/S\u00fcdtirol - P01",
    "40004",
    "Trentino-Alto Adige/S\u00fcdtirol - U04"
  ],
  [
    "camera",
    "501",
    "Veneto 1",
    "50101",
    "Veneto 1 - P01",
    "50101",
    "Veneto 1 - U01"
  ],
  [
    "camera",
    "501",
    "Veneto 1",
    "50101",
    "Veneto 1 - P01",
    "50102",
    "Veneto 1 - U02"
  ],
  [
    "camera",
    "501",
    "Veneto 1",
    "50101",
    "Veneto 1 - P01",
    "50103",
    "Veneto 1 - U03"
  ],
  [
    "camera",
    "501",
    "Veneto 1",
    "50101",
    "Veneto 1 - P01",
    "50104",
    "Veneto 1 - U04"
  ],
  [
    "camera",
    "501",
    "Veneto 1",
    "50101",
    "Veneto 1 - P01",
    "50105",
    "Veneto 1 - U05"
  ],
  [
    "camera",
    "502",
    "Veneto 2",
    "50201",
    "Veneto 2 - P01",
    "50201",
    "Veneto 2 - U01"
  ],
  [
    "camera",
    "502",
    "Veneto 2",
    "50201",
    "Veneto 2 - P01",
    "50202",
    "Veneto 2 - U02"
  ],
  [
    "camera",
    "502",
    "Veneto 2",
    "50201",
    "Veneto 2 - P01",
    "50203",
    "Veneto 2 - U03"
  ],
  [
    "camera",
    "502",
    "Veneto 2",
    "50202",
    "Veneto 2 - P02",
    "50204",
    "Veneto 2 - U04"
  ],
  [
    "camera",
    "502",
    "Veneto 2",
    "50202",
    "Veneto 2 - P02",
    "50205",
    "Veneto 2 - U05"
  ],
  [
    "camera",
    "502",
    "Veneto 2",
    "50203",
    "Veneto 2 - P03",
    "50206",
    "Veneto 2 - U06"
  ],
  [
    "camera",
    "502",
    "Veneto 2",
    "50203",
    "Veneto 2 - P03",
    "50207",
    "Veneto 2 - U07"
  ],
  [
    "camera",
    "601",
    "Friuli-Venezia Giulia",
    "60001",
    "Friuli-Venezia Giulia - P01",
    "60001",
    "Friuli-Venezia Giulia - U01"
  ],
  [
    "camera",
    "601",
    "Friuli-Venezia Giulia",
    "60001",
    "Friuli-Venezia Giulia - P01",
    "60002",
    "Friuli-Venezia Giulia - U02"
  ],
  [
    "camera",
    "601",
    "Friuli-Venezia Giulia",
    "60001",
    "Friuli-Venezia Giulia - P01",
    "60003",
    "Friuli-Venezia Giulia - U03"
  ],
  [
    "camera",
    "701",
    "Liguria",
    "70001",
    "Liguria - P01",
    "70001",
    "Liguria - U01"
  ],
  [
    "camera",
    "701",
    "Liguria",
    "70001",
    "Liguria - P01",
    "70002",
    "Liguria - U02"
  ],
  [
    "camera",
    "701",
    "Liguria",
    "70001",
    "Liguria - P01",
    "70003",
    "Liguria - U03"
  ],
  [
    "camera",
    "701",
    "Liguria",
    "70001",
    "Liguria - P01",
    "70004",
    "Liguria - U04"
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80001",
    "Emilia-Romagna - P01",
    "80001",
    "Emilia-Romagna - U01"
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80001",
    "Emilia-Romagna - P01",
    "80002",
    "Emilia-Romagna - U02"
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80001",
    "Emilia-Romagna - P01",
    "80003",
    "Emilia-Romagna - U03"
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80002",
    "Emilia-Romagna - P02",
    "80004",
    "Emilia-Romagna - U04"
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80002",
    "Emilia-Romagna - P02",
    "80005",
    "Emilia-Romagna - U05"
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80002",
    "Emilia-Romagna - P02",
    "80006",
    "Emilia-Romagna - U06"
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80002",
    "Emilia-Romagna - P02",
    "80007",
    "Emilia-Romagna - U07"
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80003",
    "Emilia-Romagna - P03",
    "80008",
    "Emilia-Romagna - U08"
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80003",
    "Emilia-Romagna - P03",
    "80009",
    "Emilia-Romagna - U09"
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80003",
    "Emilia-Romagna - P03",
    "80010",
    "Emilia-Romagna - U10"
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80003",
    "Emilia-Romagna - P03",
    "80011",
    "Emilia-Romagna - U11"
  ],
  [
    "camera",
    "901",
    "Toscana",
    "90001",
    "Toscana - P01",
    "90002",
    "Toscana - U02"
  ],
  [
    "camera",
    "901",
    "Toscana",
    "90001",
    "Toscana - P01",
    "90003",
    "Toscana - U03"
  ],
  [
    "camera",
    "901",
    "Toscana",
    "90001",
    "Toscana - P01",
    "90006",
    "Toscana - U06"
  ],
  [
    "camera",
    "901",
    "Toscana",
    "90002",
    "Toscana - P02",
    "90001",
    "Toscana - U01"
  ],
  [
    "camera",
    "901",
    "Toscana",
    "90002",
    "Toscana - P02",
    "90005",
    "Toscana - U05"
  ],
  [
    "camera",
    "901",
    "Toscana",
    "90002",
    "Toscana - P02",
    "90009",
    "Toscana - U09"
  ],
  [
    "camera",
    "901",
    "Toscana",
    "90003",
    "Toscana - P03",
    "90004",
    "Toscana - U04"
  ],
  [
    "camera",
    "901",
    "Toscana",
    "90003",
    "Toscana - P03",
    "90007",
    "Toscana - U07"
  ],
  [
    "camera",
    "901",
    "Toscana",
    "90003",
    "Toscana - P03",
    "90008",
    "Toscana - U08"
  ],
  [
    "camera",
    "1001",
    "Umbria",
    "100001",
    "Umbria - P01",
    "100001",
    "Umbria - U01"
  ],
  [
    "camera",
    "1001",
    "Umbria",
    "100001",
    "Umbria - P01",
    "100002",
    "Umbria - U02"
  ],
  [
    "camera",
    "1101",
    "Marche",
    "110001",
    "Marche - P01",
    "110001",
    "Marche - U01"
  ],
  [
    "camera",
    "1101",
    "Marche",
    "110001",
    "Marche - P01",
    "110002",
    "Marche - U02"
  ],
  [
    "camera",
    "1101",
    "Marche",
    "110001",
    "Marche - P01",
    "110003",
    "Marche - U03"
  ],
  [
    "camera",
    "1101",
    "Marche",
    "110001",
    "Marche - P01",
    "110004",
    "Marche - U04"
  ],
  [
    "camera",
    "1201",
    "Lazio 1",
    "120101",
    "Lazio 1 - P01",
    "120101",
    "Lazio 1 - U01"
  ],
  [
    "camera",
    "1201",
    "Lazio 1",
    "120101",
    "Lazio 1 - P01",
    "120102",
    "Lazio 1 - U02"
  ],
  [
    "camera",
    "1201",
    "Lazio 1",
    "120101",
    "Lazio 1 - P01",
    "120103",
    "Lazio 1 - U03"
  ],
  [
    "camera",
    "1201",
    "Lazio 1",
    "120102",
    "Lazio 1 - P02",
    "120104",
    "Lazio 1 - U04"
  ],
  [
    "camera",
    "1201",
    "Lazio 1",
    "120102",
    "Lazio 1 - P02",
    "120108",
    "Lazio 1 - U08"
  ],
  [
    "camera",
    "1201",
    "Lazio 1",
    "120102",
    "Lazio 1 - P02",
    "120109",
    "Lazio 1 - U09"
  ],
  [
    "camera",
    "1201",
    "Lazio 1",
    "120103",
    "Lazio 1 - P03",
    "120105",
    "Lazio 1 - U05"
  ],
  [
    "camera",
    "1201",
    "Lazio 1",
    "120103",
    "Lazio 1 - P03",
    "120106",
    "Lazio 1 - U06"
  ],
  [
    "camera",
    "1201",
    "Lazio 1",
    "120103",
    "Lazio 1 - P03",
    "120107",
    "Lazio 1 - U07"
  ],
  [
    "camera",
    "1202",
    "Lazio 2",
    "120201",
    "Lazio 2 - P01",
    "120201",
    "Lazio 2 - U01"
  ],
  [
    "camera",
    "1202",
    "Lazio 2",
    "120201",
    "Lazio 2 - P01",
    "120202",
    "Lazio 2 - U02"
  ],
  [
    "camera",
    "1202",
    "Lazio 2",
    "120202",
    "Lazio 2 - P02",
    "120203",
    "Lazio 2 - U03"
  ],
  [
    "camera",
    "1202",
    "Lazio 2",
    "120202",
    "Lazio 2 - P02",
    "120204",
    "Lazio 2 - U04"
  ],
  [
    "camera",
    "1202",
    "Lazio 2",
    "120202",
    "Lazio 2 - P02",
    "120205",
    "Lazio 2 - U05"
  ],
  [
    "camera",
    "1301",
    "Abruzzo",
    "130001",
    "Abruzzo - P01",
    "130001",
    "Abruzzo - U01"
  ],
  [
    "camera",
    "1301",
    "Abruzzo",
    "130001",
    "Abruzzo - P01",
    "130002",
    "Abruzzo - U02"
  ],
  [
    "camera",
    "1301",
    "Abruzzo",
    "130001",
    "Abruzzo - P01",
    "130003",
    "Abruzzo - U03"
  ],
  [
    "camera",
    "1401",
    "Molise",
    "140001",
    "Molise - P01",
    "140001",
    "Molise - U01"
  ],
  [
    "camera",
    "1501",
    "Campania 1",
    "150101",
    "Campania 1 - P01",
    "150101",
    "Campania 1 - U01"
  ],
  [
    "camera",
    "1501",
    "Campania 1",
    "150101",
    "Campania 1 - P01",
    "150102",
    "Campania 1 - U02"
  ],
  [
    "camera",
    "1501",
    "Campania 1",
    "150101",
    "Campania 1 - P01",
    "150103",
    "Campania 1 - U03"
  ],
  [
    "camera",
    "1501",
    "Campania 1",
    "150102",
    "Campania 1 - P02",
    "150104",
    "Campania 1 - U04"
  ],
  [
    "camera",
    "1501",
    "Campania 1",
    "150102",
    "Campania 1 - P02",
    "150105",
    "Campania 1 - U05"
  ],
  [
    "camera",
    "1501",
    "Campania 1",
    "150102",
    "Campania 1 - P02",
    "150106",
    "Campania 1 - U06"
  ],
  [
    "camera",
    "1501",
    "Campania 1",
    "150102",
    "Campania 1 - P02",
    "150107",
    "Campania 1 - U07"
  ],
  [
    "camera",
    "1502",
    "Campania 2",
    "150201",
    "Campania 2 - P01",
    "150201",
    "Campania 2 - U01"
  ],
  [
    "camera",
    "1502",
    "Campania 2",
    "150201",
    "Campania 2 - P01",
    "150202",
    "Campania 2 - U02"
  ],
  [
    "camera",
    "1502",
    "Campania 2",
    "150201",
    "Campania 2 - P01",
    "150203",
    "Campania 2 - U03"
  ],
  [
    "camera",
    "1502",
    "Campania 2",
    "150202",
    "Campania 2 - P02",
    "150204",
    "Campania 2 - U04"
  ],
  [
    "camera",
    "1502",
    "Campania 2",
    "150202",
    "Campania 2 - P02",
    "150205",
    "Campania 2 - U05"
  ],
  [
    "camera",
    "1502",
    "Campania 2",
    "150202",
    "Campania 2 - P02",
    "150206",
    "Campania 2 - U06"
  ],
  [
    "camera",
    "1502",
    "Campania 2",
    "150202",
    "Campania 2 - P02",
    "150207",
    "Campania 2 - U07"
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160001",
    "Puglia - P01",
    "160001",
    "Puglia - U01"
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160001",
    "Puglia - P01",
    "160002",
    "Puglia - U02"
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160001",
    "Puglia - P01",
    "160003",
    "Puglia - U03"
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160002",
    "Puglia - P02",
    "160004",
    "Puglia - U04"
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160002",
    "Puglia - P02",
    "160005",
    "Puglia - U05"
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160003",
    "Puglia - P03",
    "160006",
    "Puglia - U06"
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160003",
    "Puglia - P03",
    "160008",
    "Puglia - U08"
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160004",
    "Puglia - P04",
    "160007",
    "Puglia - U07"
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160004",
    "Puglia - P04",
    "160009",
    "Puglia - U09"
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160004",
    "Puglia - P04",
    "160010",
    "Puglia - U10"
  ],
  [
    "camera",
    "1701",
    "Basilicata",
    "170001",
    "Basilicata - P01",
    "170001",
    "Basilicata - U01"
  ],
  [
    "camera",
    "1801",
    "Calabria",
    "180001",
    "Calabria - P01",
    "180001",
    "Calabria - U01"
  ],
  [
    "camera",
    "1801",
    "Calabria",
    "180001",
    "Calabria - P01",
    "180002",
    "Calabria - U02"
  ],
  [
    "camera",
    "1801",
    "Calabria",
    "180001",
    "Calabria - P01",
    "180003",
    "Calabria - U03"
  ],
  [
    "camera",
    "1801",
    "Calabria",
    "180001",
    "Calabria - P01",
    "180004",
    "Calabria - U04"
  ],
  [
    "camera",
    "1801",
    "Calabria",
    "180001",
    "Calabria - P01",
    "180005",
    "Calabria - U05"
  ],
  [
    "camera",
    "1901",
    "Sicilia 1",
    "190101",
    "Sicilia 1 - P01",
    "190101",
    "Sicilia 1 - U01"
  ],
  [
    "camera",
    "1901",
    "Sicilia 1",
    "190101",
    "Sicilia 1 - P01",
    "190102",
    "Sicilia 1 - U02"
  ],
  [
    "camera",
    "1901",
    "Sicilia 1",
    "190101",
    "Sicilia 1 - P01",
    "190103",
    "Sicilia 1 - U03"
  ],
  [
    "camera",
    "1901",
    "Sicilia 1",
    "190102",
    "Sicilia 1 - P02",
    "190104",
    "Sicilia 1 - U04"
  ],
  [
    "camera",
    "1901",
    "Sicilia 1",
    "190102",
    "Sicilia 1 - P02",
    "190105",
    "Sicilia 1 - U05"
  ],
  [
    "camera",
    "1901",
    "Sicilia 1",
    "190102",
    "Sicilia 1 - P02",
    "190106",
    "Sicilia 1 - U06"
  ],
  [
    "camera",
    "1902",
    "Sicilia 2",
    "190201",
    "Sicilia 2 - P01",
    "190205",
    "Sicilia 2 - U05"
  ],
  [
    "camera",
    "1902",
    "Sicilia 2",
    "190201",
    "Sicilia 2 - P01",
    "190206",
    "Sicilia 2 - U06"
  ],
  [
    "camera",
    "1902",
    "Sicilia 2",
    "190202",
    "Sicilia 2 - P02",
    "190202",
    "Sicilia 2 - U02"
  ],
  [
    "camera",
    "1902",
    "Sicilia 2",
    "190202",
    "Sicilia 2 - P02",
    "190203",
    "Sicilia 2 - U03"
  ],
  [
    "camera",
    "1902",
    "Sicilia 2",
    "190203",
    "Sicilia 2 - P03",
    "190201",
    "Sicilia 2 - U01"
  ],
  [
    "camera",
    "1902",
    "Sicilia 2",
    "190203",
    "Sicilia 2 - P03",
    "190204",
    "Sicilia 2 - U04"
  ],
  [
    "camera",
    "2001",
    "Sardegna",
    "200001",
    "Sardegna - P01",
    "200001",
    "Sardegna - U01"
  ],
  [
    "camera",
    "2001",
    "Sardegna",
    "200001",
    "Sardegna - P01",
    "200002",
    "Sardegna - U02"
  ],
  [
    "camera",
    "2001",
    "Sardegna",
    "200001",
    "Sardegna - P01",
    "200003",
    "Sardegna - U03"
  ],
  [
    "camera",
    "2001",
    "Sardegna",
    "200001",
    "Sardegna - P01",
    "200004",
    "Sardegna - U04"
  ],
  [
    "senato",
    "1",
    "Piemonte",
    "10001",
    "Piemonte - P01",
    "10001",
    "Piemonte - U01"
  ],
  [
    "senato",
    "1",
    "Piemonte",
    "10001",
    "Piemonte - P01",
    "10002",
    "Piemonte - U02"
  ],
  [
    "senato",
    "1",
    "Piemonte",
    "10002",
    "Piemonte - P02",
    "10003",
    "Piemonte - U03"
  ],
  [
    "senato",
    "1",
    "Piemonte",
    "10002",
    "Piemonte - P02",
    "10004",
    "Piemonte - U04"
  ],
  [
    "senato",
    "1",
    "Piemonte",
    "10002",
    "Piemonte - P02",
    "10005",
    "Piemonte - U05"
  ],
  [
    "senato",
    "2",
    "Valle d'Aosta",
    "",
    "",
    "20001",
    "Valle d'aosta/Vall\u00e9e d'Aoste - U01"
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30001",
    "Lombardia - P01",
    "30001",
    "Lombardia - U01"
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30001",
    "Lombardia - P01",
    "30002",
    "Lombardia - U02"
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30001",
    "Lombardia - P01",
    "30006",
    "Lombardia - U06"
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30002",
    "Lombardia - P02",
    "30003",
    "Lombardia - U03"
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30002",
    "Lombardia - P02",
    "30004",
    "Lombardia - U04"
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30002",
    "Lombardia - P02",
    "30005",
    "Lombardia - U05"
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30002",
    "Lombardia - P02",
    "30010",
    "Lombardia - U10"
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30003",
    "Lombardia - P03",
    "30007",
    "Lombardia - U07"
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30003",
    "Lombardia - P03",
    "30008",
    "Lombardia - U08"
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30003",
    "Lombardia - P03",
    "30009",
    "Lombardia - U09"
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30003",
    "Lombardia - P03",
    "30011",
    "Lombardia - U11"
  ],
  [
    "senato",
    "4",
    "Trentino-Alto Adige",
    "",
    "",
    "40001",
    "Trentino-Alto Adige/S\u00fcdtirol - U01"
  ],
  [
    "senato",
    "4",
    "Trentino-Alto Adige",
    "",
    "",
    "40002",
    "Trentino-Alto Adige/S\u00fcdtirol - U02"
  ],
  [
    "senato",
    "4",
    "Trentino-Alto Adige",
    "",
    "",
    "40003",
    "Trentino-Alto Adige/S\u00fcdtirol - U03"
  ],
  [
    "senato",
    "4",
    "Trentino-Alto Adige",
    "",
    "",
    "40004",
    "Trentino-Alto Adige/S\u00fcdtirol - U04"
  ],
  [
    "senato",
    "4",
    "Trentino-Alto Adige",
    "",
    "",
    "40005",
    "Trentino-Alto Adige/S\u00fcdtirol - U05"
  ],
  [
    "senato",
    "4",
    "Trentino-Alto Adige",
    "",
    "",
    "40006",
    "Trentino-Alto Adige/S\u00fcdtirol - U06"
  ],
  [
    "senato",
    "5",
    "Veneto",
    "50001",
    "Veneto - P01",
    "50001",
    "Veneto - U01"
  ],
  [
    "senato",
    "5",
    "Veneto",
    "50001",
    "Veneto - P01",
    "50002",
    "Veneto - U02"
  ],
  [
    "senato",
    "5",
    "Veneto",
    "50002",
    "Veneto - P02",
    "50003",
    "Veneto - U03"
  ],
  [
    "senato",
    "5",
    "Veneto",
    "50002",
    "Veneto - P02",
    "50004",
    "Veneto - U04"
  ],
  [
    "senato",
    "5",
    "Veneto",
    "50002",
    "Veneto - P02",
    "50005",
    "Veneto - U05"
  ],
  [
    "senato",
    "6",
    "Friuli-Venezia Giulia",
    "60001",
    "Friuli-Venezia Giulia - P01",
    "60001",
    "Friuli-Venezia Giulia - U01"
  ],
  [
    "senato",
    "7",
    "Liguria",
    "70001",
    "Liguria - P01",
    "70001",
    "Liguria - U01"
  ],
  [
    "senato",
    "7",
    "Liguria",
    "70001",
    "Liguria - P01",
    "70002",
    "Liguria - U02"
  ],
  [
    "senato",
    "8",
    "Emilia-Romagna",
    "80001",
    "Emilia-Romagna - P01",
    "80001",
    "Emilia-Romagna - U01"
  ],
  [
    "senato",
    "8",
    "Emilia-Romagna",
    "80001",
    "Emilia-Romagna - P01",
    "80002",
    "Emilia-Romagna - U02"
  ],
  [
    "senato",
    "8",
    "Emilia-Romagna",
    "80002",
    "Emilia-Romagna - P02",
    "80003",
    "Emilia-Romagna - U03"
  ],
  [
    "senato",
    "8",
    "Emilia-Romagna",
    "80002",
    "Emilia-Romagna - P02",
    "80004",
    "Emilia-Romagna - U04"
  ],
  [
    "senato",
    "8",
    "Emilia-Romagna",
    "80002",
    "Emilia-Romagna - P02",
    "80005",
    "Emilia-Romagna - U05"
  ],
  [
    "senato",
    "9",
    "Toscana",
    "90001",
    "Toscana - P01",
    "90001",
    "Toscana - U01"
  ],
  [
    "senato",
    "9",
    "Toscana",
    "90001",
    "Toscana - P01",
    "90002",
    "Toscana - U02"
  ],
  [
    "senato",
    "9",
    "Toscana",
    "90001",
    "Toscana - P01",
    "90003",
    "Toscana - U03"
  ],
  [
    "senato",
    "9",
    "Toscana",
    "90001",
    "Toscana - P01",
    "90004",
    "Toscana - U04"
  ],
  [
    "senato",
    "10",
    "Umbria",
    "100001",
    "Umbria - P01",
    "100001",
    "Umbria - U01"
  ],
  [
    "senato",
    "11",
    "Marche",
    "110001",
    "Marche - P01",
    "110001",
    "Marche - U01"
  ],
  [
    "senato",
    "11",
    "Marche",
    "110001",
    "Marche - P01",
    "110002",
    "Marche - U02"
  ],
  [
    "senato",
    "12",
    "Lazio",
    "120001",
    "Lazio - P01",
    "120002",
    "Lazio - U02"
  ],
  [
    "senato",
    "12",
    "Lazio",
    "120001",
    "Lazio - P01",
    "120003",
    "Lazio - U03"
  ],
  [
    "senato",
    "12",
    "Lazio",
    "120001",
    "Lazio - P01",
    "120004",
    "Lazio - U04"
  ],
  [
    "senato",
    "12",
    "Lazio",
    "120002",
    "Lazio - P02",
    "120001",
    "Lazio - U01"
  ],
  [
    "senato",
    "12",
    "Lazio",
    "120002",
    "Lazio - P02",
    "120005",
    "Lazio - U05"
  ],
  [
    "senato",
    "12",
    "Lazio",
    "120002",
    "Lazio - P02",
    "120006",
    "Lazio - U06"
  ],
  [
    "senato",
    "13",
    "Abruzzo",
    "130001",
    "Abruzzo - P01",
    "130001",
    "Abruzzo - U01"
  ],
  [
    "senato",
    "14",
    "Molise",
    "140001",
    "Molise - P01",
    "140001",
    "Molise - U01"
  ],
  [
    "senato",
    "15",
    "Campania",
    "150001",
    "Campania - P01",
    "150004",
    "Campania - U04"
  ],
  [
    "senato",
    "15",
    "Campania",
    "150001",
    "Campania - P01",
    "150005",
    "Campania - U05"
  ],
  [
    "senato",
    "15",
    "Campania",
    "150001",
    "Campania - P01",
    "150006",
    "Campania - U06"
  ],
  [
    "senato",
    "15",
    "Campania",
    "150001",
    "Campania - P01",
    "150007",
    "Campania - U07"
  ],
  [
    "senato",
    "15",
    "Campania",
    "150002",
    "Campania - P02",
    "150001",
    "Campania - U01"
  ],
  [
    "senato",
    "15",
    "Campania",
    "150002",
    "Campania - P02",
    "150002",
    "Campania - U02"
  ],
  [
    "senato",
    "15",
    "Campania",
    "150002",
    "Campania - P02",
    "150003",
    "Campania - U03"
  ],
  [
    "senato",
    "16",
    "Puglia",
    "160001",
    "Puglia - P01",
    "160001",
    "Puglia - U01"
  ],
  [
    "senato",
    "16",
    "Puglia",
    "160001",
    "Puglia - P01",
    "160002",
    "Puglia - U02"
  ],
  [
    "senato",
    "16",
    "Puglia",
    "160001",
    "Puglia - P01",
    "160003",
    "Puglia - U03"
  ],
  [
    "senato",
    "16",
    "Puglia",
    "160001",
    "Puglia - P01",
    "160004",
    "Puglia - U04"
  ],
  [
    "senato",
    "16",
    "Puglia",
    "160001",
    "Puglia - P01",
    "160005",
    "Puglia - U05"
  ],
  [
    "senato",
    "17",
    "Basilicata",
    "170001",
    "Basilicata - P01",
    "170001",
    "Basilicata - U01"
  ],
  [
    "senato",
    "18",
    "Calabria",
    "180001",
    "Calabria - P01",
    "180001",
    "Calabria - U01"
  ],
  [
    "senato",
    "18",
    "Calabria",
    "180001",
    "Calabria - P01",
    "180002",
    "Calabria - U02"
  ],
  [
    "senato",
    "19",
    "Sicilia",
    "190001",
    "Sicilia - P01",
    "190001",
    "Sicilia - U01"
  ],
  [
    "senato",
    "19",
    "Sicilia",
    "190001",
    "Sicilia - P01",
    "190002",
    "Sicilia - U02"
  ],
  [
    "senato",
    "19",
    "Sicilia",
    "190001",
    "Sicilia - P01",
    "190003",
    "Sicilia - U03"
  ],
  [
    "senato",
    "19",
    "Sicilia",
    "190002",
    "Sicilia - P02",
    "190004",
    "Sicilia - U04"
  ],
  [
    "senato",
    "19",
    "Sicilia",
    "190002",
    "Sicilia - P02",
    "190005",
    "Sicilia - U05"
  ],
  [
    "senato",
    "19",
    "Sicilia",
    "190002",
    "Sicilia - P02",
    "190006",
    "Sicilia - U06"
  ],
  [
    "senato",
    "20",
    "Sardegna",
    "200001",
    "Sardegna - P01",
    "200001",
    "Sardegna - U01"
  ],
  [
    "senato",
    "20",
    "Sardegna",
    "200001",
    "Sardegna - P01",
    "200002",
    "Sardegna - U02"
  ]
];

const plurinominalRows: PlurinominalSlotTuple[] = [
  [
    "camera",
    "101",
    "Piemonte 1",
    "10101",
    "Piemonte 1 - P01",
    5,
    4
  ],
  [
    "camera",
    "101",
    "Piemonte 1",
    "10102",
    "Piemonte 1 - P02",
    5,
    4
  ],
  [
    "camera",
    "102",
    "Piemonte 2",
    "10201",
    "Piemonte 2 - P01",
    4,
    4
  ],
  [
    "camera",
    "102",
    "Piemonte 2",
    "10202",
    "Piemonte 2 - P02",
    5,
    4
  ],
  [
    "camera",
    "301",
    "Lombardia 1",
    "30101",
    "Lombardia 1 - P01",
    9,
    4
  ],
  [
    "camera",
    "301",
    "Lombardia 1",
    "30102",
    "Lombardia 1 - P02",
    9,
    4
  ],
  [
    "camera",
    "302",
    "Lombardia 2",
    "30201",
    "Lombardia 2 - P01",
    4,
    4
  ],
  [
    "camera",
    "302",
    "Lombardia 2",
    "30202",
    "Lombardia 2 - P02",
    5,
    4
  ],
  [
    "camera",
    "303",
    "Lombardia 3",
    "30301",
    "Lombardia 3 - P01",
    5,
    4
  ],
  [
    "camera",
    "303",
    "Lombardia 3",
    "30302",
    "Lombardia 3 - P02",
    5,
    4
  ],
  [
    "camera",
    "304",
    "Lombardia 4",
    "30401",
    "Lombardia 4 - P01",
    7,
    4
  ],
  [
    "camera",
    "401",
    "Trentino-Alto Adige/S\u00fcdtirol",
    "40001",
    "Trentino-Alto Adige/S\u00fcdtirol - P01",
    3,
    3
  ],
  [
    "camera",
    "501",
    "Veneto 1",
    "50101",
    "Veneto 1 - P01",
    8,
    4
  ],
  [
    "camera",
    "502",
    "Veneto 2",
    "50201",
    "Veneto 2 - P01",
    4,
    4
  ],
  [
    "camera",
    "502",
    "Veneto 2",
    "50202",
    "Veneto 2 - P02",
    4,
    4
  ],
  [
    "camera",
    "502",
    "Veneto 2",
    "50203",
    "Veneto 2 - P03",
    4,
    4
  ],
  [
    "camera",
    "601",
    "Friuli-Venezia Giulia",
    "60001",
    "Friuli-Venezia Giulia - P01",
    5,
    4
  ],
  [
    "camera",
    "701",
    "Liguria",
    "70001",
    "Liguria - P01",
    6,
    4
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80001",
    "Emilia-Romagna - P01",
    5,
    4
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80002",
    "Emilia-Romagna - P02",
    7,
    4
  ],
  [
    "camera",
    "801",
    "Emilia-Romagna",
    "80003",
    "Emilia-Romagna - P03",
    6,
    4
  ],
  [
    "camera",
    "901",
    "Toscana",
    "90001",
    "Toscana - P01",
    5,
    4
  ],
  [
    "camera",
    "901",
    "Toscana",
    "90002",
    "Toscana - P02",
    5,
    4
  ],
  [
    "camera",
    "901",
    "Toscana",
    "90003",
    "Toscana - P03",
    5,
    4
  ],
  [
    "camera",
    "1001",
    "Umbria",
    "100001",
    "Umbria - P01",
    4,
    4
  ],
  [
    "camera",
    "1101",
    "Marche",
    "110001",
    "Marche - P01",
    6,
    4
  ],
  [
    "camera",
    "1201",
    "Lazio 1",
    "120101",
    "Lazio 1 - P01",
    5,
    4
  ],
  [
    "camera",
    "1201",
    "Lazio 1",
    "120102",
    "Lazio 1 - P02",
    6,
    4
  ],
  [
    "camera",
    "1201",
    "Lazio 1",
    "120103",
    "Lazio 1 - P03",
    5,
    4
  ],
  [
    "camera",
    "1202",
    "Lazio 2",
    "120201",
    "Lazio 2 - P01",
    4,
    4
  ],
  [
    "camera",
    "1202",
    "Lazio 2",
    "120202",
    "Lazio 2 - P02",
    4,
    4
  ],
  [
    "camera",
    "1301",
    "Abruzzo",
    "130001",
    "Abruzzo - P01",
    5,
    4
  ],
  [
    "camera",
    "1401",
    "Molise",
    "140001",
    "Molise - P01",
    1,
    2
  ],
  [
    "camera",
    "1501",
    "Campania 1",
    "150101",
    "Campania 1 - P01",
    6,
    4
  ],
  [
    "camera",
    "1501",
    "Campania 1",
    "150102",
    "Campania 1 - P02",
    7,
    4
  ],
  [
    "camera",
    "1502",
    "Campania 2",
    "150201",
    "Campania 2 - P01",
    5,
    4
  ],
  [
    "camera",
    "1502",
    "Campania 2",
    "150202",
    "Campania 2 - P02",
    5,
    4
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160001",
    "Puglia - P01",
    3,
    3
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160002",
    "Puglia - P02",
    4,
    4
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160003",
    "Puglia - P03",
    4,
    4
  ],
  [
    "camera",
    "1601",
    "Puglia",
    "160004",
    "Puglia - P04",
    5,
    4
  ],
  [
    "camera",
    "1701",
    "Basilicata",
    "170001",
    "Basilicata - P01",
    3,
    3
  ],
  [
    "camera",
    "1801",
    "Calabria",
    "180001",
    "Calabria - P01",
    7,
    4
  ],
  [
    "camera",
    "1901",
    "Sicilia 1",
    "190101",
    "Sicilia 1 - P01",
    5,
    4
  ],
  [
    "camera",
    "1901",
    "Sicilia 1",
    "190102",
    "Sicilia 1 - P02",
    4,
    4
  ],
  [
    "camera",
    "1902",
    "Sicilia 2",
    "190201",
    "Sicilia 2 - P01",
    3,
    3
  ],
  [
    "camera",
    "1902",
    "Sicilia 2",
    "190202",
    "Sicilia 2 - P02",
    4,
    4
  ],
  [
    "camera",
    "1902",
    "Sicilia 2",
    "190203",
    "Sicilia 2 - P03",
    4,
    4
  ],
  [
    "camera",
    "2001",
    "Sardegna",
    "200001",
    "Sardegna - P01",
    6,
    4
  ],
  [
    "senato",
    "1",
    "Piemonte",
    "10001",
    "Piemonte - P01",
    4,
    4
  ],
  [
    "senato",
    "1",
    "Piemonte",
    "10002",
    "Piemonte - P02",
    5,
    4
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30001",
    "Lombardia - P01",
    6,
    4
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30002",
    "Lombardia - P02",
    9,
    4
  ],
  [
    "senato",
    "3",
    "Lombardia",
    "30003",
    "Lombardia - P03",
    6,
    4
  ],
  [
    "senato",
    "5",
    "Veneto",
    "50001",
    "Veneto - P01",
    5,
    4
  ],
  [
    "senato",
    "5",
    "Veneto",
    "50002",
    "Veneto - P02",
    6,
    4
  ],
  [
    "senato",
    "6",
    "Friuli-Venezia Giulia",
    "60001",
    "Friuli-Venezia Giulia - P01",
    3,
    3
  ],
  [
    "senato",
    "7",
    "Liguria",
    "70001",
    "Liguria - P01",
    3,
    3
  ],
  [
    "senato",
    "8",
    "Emilia-Romagna",
    "80001",
    "Emilia-Romagna - P01",
    4,
    4
  ],
  [
    "senato",
    "8",
    "Emilia-Romagna",
    "80002",
    "Emilia-Romagna - P02",
    5,
    4
  ],
  [
    "senato",
    "9",
    "Toscana",
    "90001",
    "Toscana - P01",
    8,
    4
  ],
  [
    "senato",
    "10",
    "Umbria",
    "100001",
    "Umbria - P01",
    2,
    2
  ],
  [
    "senato",
    "11",
    "Marche",
    "110001",
    "Marche - P01",
    3,
    3
  ],
  [
    "senato",
    "12",
    "Lazio",
    "120001",
    "Lazio - P01",
    6,
    4
  ],
  [
    "senato",
    "12",
    "Lazio",
    "120002",
    "Lazio - P02",
    6,
    4
  ],
  [
    "senato",
    "13",
    "Abruzzo",
    "130001",
    "Abruzzo - P01",
    3,
    3
  ],
  [
    "senato",
    "14",
    "Molise",
    "140001",
    "Molise - P01",
    1,
    1
  ],
  [
    "senato",
    "15",
    "Campania",
    "150001",
    "Campania - P01",
    6,
    4
  ],
  [
    "senato",
    "15",
    "Campania",
    "150002",
    "Campania - P02",
    5,
    4
  ],
  [
    "senato",
    "16",
    "Puglia",
    "160001",
    "Puglia - P01",
    8,
    4
  ],
  [
    "senato",
    "17",
    "Basilicata",
    "170001",
    "Basilicata - P01",
    2,
    2
  ],
  [
    "senato",
    "18",
    "Calabria",
    "180001",
    "Calabria - P01",
    4,
    4
  ],
  [
    "senato",
    "19",
    "Sicilia",
    "190001",
    "Sicilia - P01",
    4,
    4
  ],
  [
    "senato",
    "19",
    "Sicilia",
    "190002",
    "Sicilia - P02",
    5,
    4
  ],
  [
    "senato",
    "20",
    "Sardegna",
    "200001",
    "Sardegna - P01",
    3,
    3
  ]
];

export const generatedPoliticsCandidateSlots: PoliticsCandidateSlotCatalog = {
  uninominal: uninominalRows.map(
    ([ramo, circCode, circLabel, pluriCode, pluriLabel, uninominalCode, uninominalLabel]) => ({
      ramo: ramo === 'senato' ? 'senato' : 'camera',
      circCode,
      circLabel,
      pluriCode,
      pluriLabel,
      uninominalCode,
      uninominalLabel
    })
  ),
  plurinominal: plurinominalRows.map(([ramo, circCode, circLabel, pluriCode, pluriLabel, seats, maxCandidates]) => ({
    ramo: ramo === 'senato' ? 'senato' : 'camera',
    circCode,
    circLabel,
    pluriCode,
    pluriLabel,
    seats,
    maxCandidates
  }))
};
