// Generated by scripts/export_politics_scenario_defaults.mjs from web/static/data/v1/politics-static.json.
// Do not edit this file by hand.

import type { Scenario } from '$lib/core/types';

export const generatedDefaultPoliticsScenario = {
  "id": "politiche-2027",
  "name": "Politiche 2027",
  "electionDate": "2027-03-01",
  "defaultSource": {
    "kind": "bundled",
    "electionKind": "politiche",
    "territory": "Italia",
    "dataVersion": "v1",
    "snapshotId": "politics-static.json"
  },
  "globalShareMode": "mean",
  "abstentionShare": 55.18,
  "abstentionOverride": false,
  "coalitions": [
    {
      "id": "sinistra",
      "name": "sinistra",
      "color": "#d94848"
    },
    {
      "id": "centro",
      "name": "centro",
      "color": "#7a6bb2"
    },
    {
      "id": "destra",
      "name": "destra",
      "color": "#3267b1"
    },
    {
      "id": "pap",
      "name": "PaP",
      "color": "#7a3b2e"
    }
  ],
  "lists": [
    {
      "id": "europa",
      "name": "+Europa",
      "coalition": "sinistra",
      "color": "#e9897e",
      "startingShare": 1.94,
      "shareOverride": false
    },
    {
      "id": "avs",
      "name": "Alleanza Verdi Sinistra",
      "coalition": "sinistra",
      "color": "#44a36f",
      "startingShare": 6.91,
      "shareOverride": false
    },
    {
      "id": "azione-iv",
      "name": "Azione - Italia Viva",
      "coalition": "centro",
      "color": "#7a6bb2",
      "startingShare": 5.38,
      "shareOverride": false
    },
    {
      "id": "fi",
      "name": "Forza Italia",
      "coalition": "destra",
      "color": "#5d8ed8",
      "startingShare": 9.9,
      "shareOverride": false
    },
    {
      "id": "fdi",
      "name": "Fratelli d'Italia",
      "coalition": "destra",
      "color": "#3267b1",
      "startingShare": 29.69,
      "shareOverride": false
    },
    {
      "id": "lega",
      "name": "Lega",
      "coalition": "destra",
      "color": "#2f8a68",
      "startingShare": 9.27,
      "shareOverride": false
    },
    {
      "id": "m5s",
      "name": "Movimento 5 Stelle",
      "coalition": "sinistra",
      "color": "#d8b400",
      "startingShare": 10.29,
      "shareOverride": false
    },
    {
      "id": "pd",
      "name": "Partito Democratico",
      "coalition": "sinistra",
      "color": "#d94848",
      "startingShare": 24.81,
      "shareOverride": false
    },
    {
      "id": "pap",
      "name": "Potere al Popolo!",
      "coalition": "PaP",
      "color": "#7a3b2e",
      "startingShare": 1.8,
      "shareOverride": false
    }
  ],
  "listCorrespondences": [
    {
      "id": "correspondence-2018-03-04-camera-2018-europa-europa",
      "futureList": "+Europa",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "+EUROPA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-10-volte-meglio-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "10 VOLTE MEGLIO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-autodeterminatzione-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "AUTODETERMINATZIONE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-blocco-nazionale-per-le-liberta-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "BLOCCO NAZIONALE PER LE LIBERTA'",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-casapound-italia-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "CASAPOUND ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-civica-popolare-lorenzin-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "CIVICA POPOLARE LORENZIN",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-fi-frat-d-it-mov-nuova-valle-d-aosta-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "FI -FRAT. D'IT. -MOV.NUOVA VALLE D'AOSTA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-forza-italia-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "FORZA ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-fratelli-d-italia-con-giorgia-meloni-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "FRATELLI D'ITALIA CON GIORGIA MELONI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-grande-nord-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "GRANDE NORD",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-il-popolo-della-famiglia-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "IL POPOLO DELLA FAMIGLIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-italia-agli-italiani-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "ITALIA AGLI ITALIANI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-italia-europa-insieme-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "ITALIA EUROPA INSIEME",
      "factor": 0.5,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-italia-europa-insieme-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "ITALIA EUROPA INSIEME",
      "factor": 0.5,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-italia-nel-cuore-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "ITALIA NEL CUORE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-lega-lega",
      "futureList": "Lega",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "LEGA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-liberi-e-uguali-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "LIBERI E UGUALI",
      "factor": 0.5,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-liberi-e-uguali-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "LIBERI E UGUALI",
      "factor": 0.5,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-lista-del-popolo-per-la-costituzione-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "LISTA DEL POPOLO PER LA COSTITUZIONE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-movimento-5-stelle-movimento-5-stelle",
      "futureList": "Movimento 5 Stelle",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "MOVIMENTO 5 STELLE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-noi-con-l-italia-udc-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "NOI CON L'ITALIA - UDC",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-partito-comunista-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "PARTITO COMUNISTA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-partito-democratico-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "PARTITO DEMOCRATICO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-partito-repubblicano-italiano-ala-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "PARTITO REPUBBLICANO ITALIANO - ALA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-partito-valore-umano-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "PARTITO VALORE UMANO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-patto-per-l-autonomia-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "PATTO PER L'AUTONOMIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-pd-uv-uvp-epav-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "PD-UV-UVP-EPAV",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-per-una-sinistra-rivoluzionaria-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "PER UNA SINISTRA RIVOLUZIONARIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-potere-al-popolo-potere-al-popolo",
      "futureList": "Potere al Popolo!",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "POTERE AL POPOLO!",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-pour-tous-per-tutti-pe-tcheut-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "POUR TOUS PER TUTTI PE TCHEUT",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-rinascimento-mir-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "RINASCIMENTO MIR",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-risposta-civica-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "RISPOSTA CIVICA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-siamo-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "SIAMO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-svp-patt-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "SVP - PATT",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-astensione-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "astensione",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-europa-europa",
      "futureList": "+Europa",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "+EUROPA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-alleanza-verdi-e-sinistra-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "ALLEANZA VERDI E SINISTRA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-alternativa-per-l-italia-no-green-pass-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "ALTERNATIVA PER L'ITALIA - NO GREEN PASS",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-azione-italia-viva-calenda-azione-italia-viva",
      "futureList": "Azione - Italia Viva",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "AZIONE - ITALIA VIVA - CALENDA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-forza-del-popolo-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "FORZA DEL POPOLO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-forza-italia-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "FORZA ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-fratelli-d-italia-con-giorgia-meloni-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "FRATELLI D'ITALIA CON GIORGIA MELONI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-free-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "FREE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-impegno-civico-luigi-di-maio-centro-democratico-movimento-5-stelle",
      "futureList": "Movimento 5 Stelle",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "IMPEGNO CIVICO LUIGI DI MAIO - CENTRO DEMOCRATICO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-italexit-per-l-italia-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "ITALEXIT PER L'ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-italia-sovrana-e-popolare-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "ITALIA SOVRANA E POPOLARE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-lega-per-salvini-premier-lega",
      "futureList": "Lega",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "LEGA PER SALVINI PREMIER",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-mastella-noi-di-centro-europeisti-azione-italia-viva",
      "futureList": "Azione - Italia Viva",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "MASTELLA NOI DI CENTRO EUROPEISTI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-movimento-5-stelle-movimento-5-stelle",
      "futureList": "Movimento 5 Stelle",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "MOVIMENTO 5 STELLE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-noi-moderati-lupi-toti-brugnaro-udc-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "NOI MODERATI/LUPI - TOTI - BRUGNARO - UDC",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-partito-animalista-ucdl-10-volte-meglio-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "PARTITO ANIMALISTA - UCDL - 10 VOLTE MEGLIO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-partito-comunista-italiano-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "PARTITO COMUNISTA ITALIANO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-partito-della-follia-creativa-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "PARTITO DELLA FOLLIA CREATIVA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-partito-democratico-italia-democratica-e-progressista-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "PARTITO DEMOCRATICO - ITALIA DEMOCRATICA E PROGRESSISTA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-sud-chiama-nord-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "SUD CHIAMA NORD",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-sudtiroler-volkspartei-svp-patt-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "SUDTIROLER VOLKSPARTEI (SVP) - PATT",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-unione-popolare-con-de-magistris-potere-al-popolo",
      "futureList": "Potere al Popolo!",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "UNIONE POPOLARE CON DE MAGISTRIS",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-vita-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "VITA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-astensione-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "astensione",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-europa-italia-in-comune-pde-italia-europa",
      "futureList": "+Europa",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "+EUROPA - ITALIA IN COMUNE - PDE ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-autonomie-per-l-europa-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "AUTONOMIE PER L'EUROPA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-casapound-italia-destre-unite-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "CASAPOUND ITALIA - DESTRE UNITE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-europa-verde-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "EUROPA VERDE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-forza-italia-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "FORZA ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-forza-nuova-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "FORZA NUOVA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-fratelli-d-italia-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "FRATELLI D'ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-la-sinistra-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "LA SINISTRA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-lega-salvini-premier-lega",
      "futureList": "Lega",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "LEGA SALVINI PREMIER",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-movimento-5-stelle-movimento-5-stelle",
      "futureList": "Movimento 5 Stelle",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "MOVIMENTO 5 STELLE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-partito-animalista-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "PARTITO ANIMALISTA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-partito-comunista-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "PARTITO COMUNISTA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-partito-democratico-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "PARTITO DEMOCRATICO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-partito-pirata-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "PARTITO PIRATA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-popolari-per-l-italia-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "POPOLARI PER L'ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-popolo-della-famiglia-alternativa-popolare-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "POPOLO DELLA FAMIGLIA - ALTERNATIVA POPOLARE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-ppa-movimento-politico-pensiero-azione-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "PPA MOVIMENTO POLITICO PENSIERO AZIONE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-svp-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "SVP",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-astensione-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "astensione",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-alleanza-verdi-e-sinistra-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "ALLEANZA VERDI E SINISTRA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-alternativa-popolare-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "ALTERNATIVA POPOLARE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-azione-siamo-europei-azione-italia-viva",
      "futureList": "Azione - Italia Viva",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "AZIONE - SIAMO EUROPEI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-democrazia-sovrana-popolare-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "DEMOCRAZIA SOVRANA POPOLARE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-forza-italia-noi-moderati-ppe-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "FORZA ITALIA - NOI MODERATI - PPE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-fratelli-d-italia-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "FRATELLI D'ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-lega-salvini-premier-lega",
      "futureList": "Lega",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "LEGA SALVINI PREMIER",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-liberta-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "LIBERTA'",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-movimento-5-stelle-movimento-5-stelle",
      "futureList": "Movimento 5 Stelle",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "MOVIMENTO 5 STELLE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-pace-terra-dignita-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "PACE TERRA DIGNITA'",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-partito-animalista-italexit-per-l-italia-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "PARTITO ANIMALISTA - ITALEXIT PER L'ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-partito-democratico-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "PARTITO DEMOCRATICO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-rassemblement-valdotain-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "RASSEMBLEMENT VALD\u00d4TAIN",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-stati-uniti-d-europa-europa",
      "futureList": "+Europa",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "STATI UNITI D'EUROPA",
      "factor": 0.5,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-stati-uniti-d-europa-azione-italia-viva",
      "futureList": "Azione - Italia Viva",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "STATI UNITI D'EUROPA",
      "factor": 0.5,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-sudtiroler-volkspartei-svp-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "S\u00dcDTIROLER VOLKSPARTEI (SVP)",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-astensione-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "astensione",
      "factor": 1,
      "source": "bundled"
    }
  ],
  "localShareOverrides": []
} satisfies Scenario;
