// Generated by scripts/export_regional_er_scenario_defaults.mjs from web/static/data/v1/regional-er-static.json.
// Do not edit this file by hand.

import type { Scenario } from '$lib/core/types';

export const generatedDefaultRegionalErScenario = {
  "id": "regionali-er-2027",
  "name": "Regionali Emilia-Romagna 2027",
  "electionDate": "2027-03-01",
  "defaultSource": {
    "kind": "bundled",
    "electionKind": "regionali-er",
    "territory": "Emilia-Romagna",
    "dataVersion": "v1",
    "snapshotId": "regional-er-static.json"
  },
  "globalShareMode": "mean",
  "abstentionShare": 58.65,
  "abstentionOverride": false,
  "coalitions": [
    {
      "id": "coalition-sinistra",
      "name": "sinistra",
      "color": "#d94848"
    },
    {
      "id": "coalition-destra",
      "name": "destra",
      "color": "#3267b1"
    },
    {
      "id": "coalition-pap",
      "name": "PaP",
      "color": "#7a3b2e"
    }
  ],
  "lists": [
    {
      "id": "list-alleanza-verdi-sinistra",
      "name": "Alleanza Verdi Sinistra",
      "coalition": "sinistra",
      "color": "#44a36f",
      "startingShare": 5.36,
      "shareOverride": false
    },
    {
      "id": "list-destra-lista-sindaco",
      "name": "Destra Lista Sindaco",
      "coalition": "destra",
      "color": "#5d8ed8",
      "startingShare": 5.21,
      "shareOverride": false
    },
    {
      "id": "list-forza-italia",
      "name": "Forza Italia",
      "coalition": "destra",
      "color": "#5d8ed8",
      "startingShare": 5.68,
      "shareOverride": false
    },
    {
      "id": "list-fratelli-d-italia",
      "name": "Fratelli d'Italia",
      "coalition": "destra",
      "color": "#3267b1",
      "startingShare": 23.99,
      "shareOverride": false
    },
    {
      "id": "list-lega",
      "name": "Lega",
      "coalition": "destra",
      "color": "#2f8a68",
      "startingShare": 5.32,
      "shareOverride": false
    },
    {
      "id": "list-movimento-5-stelle",
      "name": "Movimento 5 Stelle",
      "coalition": "sinistra",
      "color": "#d8b400",
      "startingShare": 3.59,
      "shareOverride": false
    },
    {
      "id": "list-partito-democratico",
      "name": "Partito Democratico",
      "coalition": "sinistra",
      "color": "#d94848",
      "startingShare": 43.39,
      "shareOverride": false
    },
    {
      "id": "list-potere-al-popolo",
      "name": "Potere al Popolo!",
      "coalition": "PaP",
      "color": "#7a3b2e",
      "startingShare": 1.85,
      "shareOverride": false
    },
    {
      "id": "list-sinistra-lista-sindaco",
      "name": "Sinistra Lista Sindaco",
      "coalition": "sinistra",
      "color": "#e9897e",
      "startingShare": 5.62,
      "shareOverride": false
    }
  ],
  "listCorrespondences": [
    {
      "id": "correspondence-2018-03-04-camera-2018-europa-sinistra-lista-sindaco",
      "futureList": "Sinistra Lista Sindaco",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "+EUROPA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-casapound-italia-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "CASAPOUND ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-civica-popolare-lorenzin-sinistra-lista-sindaco",
      "futureList": "Sinistra Lista Sindaco",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "CIVICA POPOLARE LORENZIN",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-forza-italia-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "FORZA ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-fratelli-d-italia-con-giorgia-meloni-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "FRATELLI D'ITALIA CON GIORGIA MELONI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-il-popolo-della-famiglia-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "IL POPOLO DELLA FAMIGLIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-italia-agli-italiani-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "ITALIA AGLI ITALIANI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-italia-europa-insieme-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "ITALIA EUROPA INSIEME",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-lega-lega",
      "futureList": "Lega",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "LEGA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-liberi-e-uguali-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "LIBERI E UGUALI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-lista-del-popolo-per-la-costituzione-sinistra-lista-sindaco",
      "futureList": "Sinistra Lista Sindaco",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "LISTA DEL POPOLO PER LA COSTITUZIONE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-movimento-5-stelle-movimento-5-stelle",
      "futureList": "Movimento 5 Stelle",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "MOVIMENTO 5 STELLE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-noi-con-l-italia-udc-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "NOI CON L'ITALIA - UDC",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-partito-comunista-potere-al-popolo",
      "futureList": "Potere al Popolo!",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "PARTITO COMUNISTA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-partito-democratico-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "PARTITO DEMOCRATICO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-partito-repubblicano-italiano-ala-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "PARTITO REPUBBLICANO ITALIANO - ALA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-partito-valore-umano-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "PARTITO VALORE UMANO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-per-una-sinistra-rivoluzionaria-potere-al-popolo",
      "futureList": "Potere al Popolo!",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "PER UNA SINISTRA RIVOLUZIONARIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-potere-al-popolo-potere-al-popolo",
      "futureList": "Potere al Popolo!",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "POTERE AL POPOLO!",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2018-03-04-camera-2018-astensione-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2018",
      "pastDate": "2018-03-04",
      "pastList": "astensione",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-europa-sinistra-lista-sindaco",
      "futureList": "Sinistra Lista Sindaco",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "+EUROPA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-alleanza-verdi-e-sinistra-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "ALLEANZA VERDI E SINISTRA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-azione-italia-viva-calenda-sinistra-lista-sindaco",
      "futureList": "Sinistra Lista Sindaco",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "AZIONE - ITALIA VIVA - CALENDA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-forza-italia-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "FORZA ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-fratelli-d-italia-con-giorgia-meloni-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "FRATELLI D'ITALIA CON GIORGIA MELONI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-impegno-civico-luigi-di-maio-centro-democratico-movimento-5-stelle",
      "futureList": "Movimento 5 Stelle",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "IMPEGNO CIVICO LUIGI DI MAIO - CENTRO DEMOCRATICO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-italexit-per-l-italia-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "ITALEXIT PER L'ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-italia-sovrana-e-popolare-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "ITALIA SOVRANA E POPOLARE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-lega-per-salvini-premier-lega",
      "futureList": "Lega",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "LEGA PER SALVINI PREMIER",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-mastella-noi-di-centro-europeisti-destra-lista-sindaco",
      "futureList": "Destra Lista Sindaco",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "MASTELLA NOI DI CENTRO EUROPEISTI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-movimento-5-stelle-movimento-5-stelle",
      "futureList": "Movimento 5 Stelle",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "MOVIMENTO 5 STELLE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-noi-moderati-lupi-toti-brugnaro-udc-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "NOI MODERATI/LUPI - TOTI - BRUGNARO - UDC",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-partito-animalista-ucdl-10-volte-meglio-destra-lista-sindaco",
      "futureList": "Destra Lista Sindaco",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "PARTITO ANIMALISTA - UCDL - 10 VOLTE MEGLIO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-partito-democratico-italia-democratica-e-progressista-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "PARTITO DEMOCRATICO - ITALIA DEMOCRATICA E PROGRESSISTA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-sud-chiama-nord-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "SUD CHIAMA NORD",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-unione-popolare-con-de-magistris-potere-al-popolo",
      "futureList": "Potere al Popolo!",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "UNIONE POPOLARE CON DE MAGISTRIS",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-vita-movimento-5-stelle",
      "futureList": "Movimento 5 Stelle",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "VITA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2022-09-25-camera-2022-astensione-astensione",
      "futureList": "astensione",
      "pastElection": "camera 2022",
      "pastDate": "2022-09-25",
      "pastList": "astensione",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-europa-italia-in-comune-pde-italia-sinistra-lista-sindaco",
      "futureList": "Sinistra Lista Sindaco",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "+EUROPA - ITALIA IN COMUNE - PDE ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-casapound-italia-destre-unite-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "CASAPOUND ITALIA - DESTRE UNITE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-europa-verde-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "EUROPA VERDE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-forza-italia-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "FORZA ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-forza-nuova-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "FORZA NUOVA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-fratelli-d-italia-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "FRATELLI D'ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-la-sinistra-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "LA SINISTRA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-lega-salvini-premier-lega",
      "futureList": "Lega",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "LEGA SALVINI PREMIER",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-movimento-5-stelle-movimento-5-stelle",
      "futureList": "Movimento 5 Stelle",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "MOVIMENTO 5 STELLE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-partito-animalista-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "PARTITO ANIMALISTA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-partito-comunista-potere-al-popolo",
      "futureList": "Potere al Popolo!",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "PARTITO COMUNISTA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-partito-democratico-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "PARTITO DEMOCRATICO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-partito-pirata-potere-al-popolo",
      "futureList": "Potere al Popolo!",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "PARTITO PIRATA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-popolari-per-l-italia-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "POPOLARI PER L'ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-popolo-della-famiglia-alternativa-popolare-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "POPOLO DELLA FAMIGLIA - ALTERNATIVA POPOLARE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-ppa-movimento-politico-pensiero-azione-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "PPA MOVIMENTO POLITICO PENSIERO AZIONE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-svp-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "SVP",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2019-05-26-europee-2019-astensione-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2019",
      "pastDate": "2019-05-26",
      "pastList": "astensione",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-alleanza-verdi-e-sinistra-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "ALLEANZA VERDI E SINISTRA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-alternativa-popolare-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "ALTERNATIVA POPOLARE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-azione-siamo-europei-sinistra-lista-sindaco",
      "futureList": "Sinistra Lista Sindaco",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "AZIONE - SIAMO EUROPEI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-forza-italia-noi-moderati-ppe-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "FORZA ITALIA - NOI MODERATI - PPE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-fratelli-d-italia-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "FRATELLI D'ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-lega-salvini-premier-lega",
      "futureList": "Lega",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "LEGA SALVINI PREMIER",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-liberta-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "LIBERTA'",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-movimento-5-stelle-movimento-5-stelle",
      "futureList": "Movimento 5 Stelle",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "MOVIMENTO 5 STELLE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-pace-terra-dignita-potere-al-popolo",
      "futureList": "Potere al Popolo!",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "PACE TERRA DIGNITA'",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-partito-democratico-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "PARTITO DEMOCRATICO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-stati-uniti-d-europa-sinistra-lista-sindaco",
      "futureList": "Sinistra Lista Sindaco",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "STATI UNITI D'EUROPA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-sudtiroler-volkspartei-svp-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "S\u00dcDTIROLER VOLKSPARTEI (SVP)",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-06-08-europee-2024-astensione-astensione",
      "futureList": "astensione",
      "pastElection": "europee 2024",
      "pastDate": "2024-06-08",
      "pastList": "astensione",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-europa-psi-pri-sinistra-lista-sindaco",
      "futureList": "Sinistra Lista Sindaco",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "+EUROPA - PSI - PRI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-bonaccini-presidente-sinistra-lista-sindaco",
      "futureList": "Sinistra Lista Sindaco",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "BONACCINI PRESIDENTE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-emilia-romagna-coraggiosa-ecologista-progressista-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "EMILIA-ROMAGNA CORAGGIOSA ECOLOGISTA PROGRESSISTA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-europa-verde-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "EUROPA VERDE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-forza-italia-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "FORZA ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-fratelli-d-italia-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "FRATELLI D'ITALIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-giovani-per-l-ambiente-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "GIOVANI PER L'AMBIENTE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-il-popolo-della-famiglia-cambiamo-astensione",
      "futureList": "astensione",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "IL POPOLO DELLA FAMIGLIA - CAMBIAMO!",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-l-altra-emilia-romagna-potere-al-popolo",
      "futureList": "Potere al Popolo!",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "L'ALTRA EMILIA ROMAGNA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-lega-lega",
      "futureList": "Lega",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "LEGA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-movimento-3v-vaccini-vogliamo-verita-astensione",
      "futureList": "astensione",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "MOVIMENTO 3V VACCINI VOGLIAMO VERITA'",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-movimento-5-stelle-movimento-5-stelle",
      "futureList": "Movimento 5 Stelle",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "MOVIMENTO 5 STELLE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-partito-comunista-potere-al-popolo",
      "futureList": "Potere al Popolo!",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "PARTITO COMUNISTA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-partito-democratico-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "PARTITO DEMOCRATICO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-potere-al-popolo-potere-al-popolo",
      "futureList": "Potere al Popolo!",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "POTERE AL POPOLO!",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-progetto-emilia-romagna-rete-civica-borgonzoni-presidente-destra-lista-sindaco",
      "futureList": "Destra Lista Sindaco",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "PROGETTO EMILIA-ROMAGNA RETE CIVICA BORGONZONI PRESIDENTE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-volt-emilia-romagna-sinistra-lista-sindaco",
      "futureList": "Sinistra Lista Sindaco",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "VOLT EMILIA-ROMAGNA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2020-01-26-regionali-2020-astensione-astensione",
      "futureList": "astensione",
      "pastElection": "regionali 2020",
      "pastDate": "2020-01-26",
      "pastList": "astensione",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-11-17-regionali-2024-astensione",
      "futureList": "astensione",
      "pastElection": "regionali 2024",
      "pastDate": "2024-11-17",
      "pastList": "",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-11-17-regionali-2024-alleanza-verdi-e-sinistra-coalizioni-civiche-possibile-alleanza-verdi-sinistra",
      "futureList": "Alleanza Verdi Sinistra",
      "pastElection": "regionali 2024",
      "pastDate": "2024-11-17",
      "pastList": "ALLEANZA VERDI E SINISTRA - COALIZIONI CIVICHE - POSSIBILE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-11-17-regionali-2024-civici-con-de-pascale-presidente-sinistra-lista-sindaco",
      "futureList": "Sinistra Lista Sindaco",
      "pastElection": "regionali 2024",
      "pastDate": "2024-11-17",
      "pastList": "CIVICI, CON DE PASCALE PRESIDENTE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-11-17-regionali-2024-emilia-romagna-per-la-pace-l-ambiente-e-il-lavoro-potere-al-popolo",
      "futureList": "Potere al Popolo!",
      "pastElection": "regionali 2024",
      "pastDate": "2024-11-17",
      "pastList": "EMILIA-ROMAGNA PER LA PACE, L'AMBIENTE E IL LAVORO",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-11-17-regionali-2024-forza-italia-berlusconi-ugolini-presidente-noi-moderati-forza-italia",
      "futureList": "Forza Italia",
      "pastElection": "regionali 2024",
      "pastDate": "2024-11-17",
      "pastList": "FORZA ITALIA - BERLUSCONI - UGOLINI PRESIDENTE - NOI MODERATI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-11-17-regionali-2024-fratelli-d-italia-giorgia-meloni-fratelli-d-italia",
      "futureList": "Fratelli d'Italia",
      "pastElection": "regionali 2024",
      "pastDate": "2024-11-17",
      "pastList": "FRATELLI D'ITALIA - GIORGIA MELONI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-11-17-regionali-2024-lealta-coerenza-verita-luca-teodori-astensione",
      "futureList": "astensione",
      "pastElection": "regionali 2024",
      "pastDate": "2024-11-17",
      "pastList": "LEALTA' COERENZA VERITA' - LUCA TEODORI",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-11-17-regionali-2024-lega-salvini-emilia-romagna-il-popolo-della-famiglia-lega",
      "futureList": "Lega",
      "pastElection": "regionali 2024",
      "pastDate": "2024-11-17",
      "pastList": "LEGA SALVINI EMILIA-ROMAGNA - IL POPOLO DELLA FAMIGLIA",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-11-17-regionali-2024-movimento-5-stelle-movimento-5-stelle",
      "futureList": "Movimento 5 Stelle",
      "pastElection": "regionali 2024",
      "pastDate": "2024-11-17",
      "pastList": "MOVIMENTO 5 STELLE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-11-17-regionali-2024-partito-democratico-de-pascale-presidente-partito-democratico",
      "futureList": "Partito Democratico",
      "pastElection": "regionali 2024",
      "pastDate": "2024-11-17",
      "pastList": "PARTITO DEMOCRATICO - DE PASCALE PRESIDENTE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-11-17-regionali-2024-rete-civica-elena-ugolini-presidente-destra-lista-sindaco",
      "futureList": "Destra Lista Sindaco",
      "pastElection": "regionali 2024",
      "pastDate": "2024-11-17",
      "pastList": "RETE CIVICA - ELENA UGOLINI PRESIDENTE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-11-17-regionali-2024-riformisti-emilia-romagna-futura-de-pascale-presidente-sinistra-lista-sindaco",
      "futureList": "Sinistra Lista Sindaco",
      "pastElection": "regionali 2024",
      "pastDate": "2024-11-17",
      "pastList": "RIFORMISTI EMILIA-ROMAGNA FUTURA - DE PASCALE PRESIDENTE",
      "factor": 1,
      "source": "bundled"
    },
    {
      "id": "correspondence-2024-11-17-regionali-2024-astensione-astensione",
      "futureList": "astensione",
      "pastElection": "regionali 2024",
      "pastDate": "2024-11-17",
      "pastList": "astensione",
      "factor": 1,
      "source": "bundled"
    }
  ],
  "localShareOverrides": [],
  "candidateTemplates": [],
  "candidateGeneration": {
    "uninominalToPlurinominalShare": 0,
    "plurinominalCandidacyCountShares": [
      1,
      0,
      0,
      0,
      0
    ]
  }
} satisfies Scenario;
