---
title: "Elezioni del comune di Bologna 2027"
author: "Luca Fornasari"
date: "`r Sys.Date()`"
format: 
  html:
    self-contained: true
---

```{r setup}
#| include: false
knitr::opts_chunk$set(echo = FALSE)

source("R/caricamento_dati.R")
source("R/generazione_voti.R")
source("R/scrutinio_comunali.R")
source("R/simula_comunali.R")
source("R/presentazione_risultati.R")

comune <- "Bologna"

scenario <- "scenari/BO_soli.xlsx"

data_elezione <- as.POSIXct("2027-03-01")

```

```{r simulazione}
#| include: false
#| cache: true

risultato <- simula_comunali(comune, scenario, data_elezione)

```

## Dati
```{r}
tabella_dati(risultato)
```

### Percentuali per lista

Questo grafico mostra le percentuali simulate per ciascuna 
lista.
```{r}
boxplot_percentuali(risultato)
```

### Coalizioni vincenti

```{r vincenti}

coalizioni_vincenti(risultato)

```

### Composizione del Consiglio comunale

```{r plot_consiglio_comunale}

plot_consiglio_comunale(risultato)

```

### Probabilità di eleggere qualcuno

```{r}
superamento_soglia_comunali(risultato)
```

### Numero di seggi rispetto alle percentuali ottenute



```{r}
# eletti_percentuale_xyplots(risultato)
```

```{r}
grafici_eletti_comunali(risultato)
```

