---
title: "Voti per i soli candidati nei collegi uninominali"
author: "Luca Fornasari"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(readxl)

# Carico i dati di voto ottenuti da Eligendo
liste_comune <- read.csv2(
  "dati_2018/camera-20180304_2.txt",
  colClasses = c(
    CIRCOSCRIZIONE = "factor",
    COLLEGIOPLURINOMINALE = "factor",
    COLLEGIOUNINOMINALE = "factor",
    COMUNE = "factor",
    SESSO = "factor",
    LISTA = "factor"
  ),
  fileEncoding = "utf-8"
)

# Carico i dati delle liste
liste_naz <- read_excel("dati_2018/dati_2018.xlsx", "camera_liste")

liste_naz$CL <- liste_naz$COALIZIONE
liste_naz$CL[is.na(liste_naz$CL)] <- liste_naz$LISTA[is.na(liste_naz$CL)]

liste_naz$LISTA <- factor(liste_naz$LISTA, levels = levels(liste_comune$LISTA))

liste_comune <- merge(
  liste_comune,
  liste_naz
)

cl_comune <- unique(
  liste_comune[, c(
    "CIRCOSCRIZIONE",
    "COLLEGIOPLURINOMINALE",
    "COLLEGIOUNINOMINALE",
    "COMUNE",
    "CL",
    "VOTI_CANDIDATO"
  )]
)

cl_comune <- merge(
  cl_comune,
  aggregate(
    VOTI_LISTA ~
      CIRCOSCRIZIONE +
      COLLEGIOPLURINOMINALE +
      COLLEGIOUNINOMINALE +
      COMUNE +
      CL,
    liste_comune,
    sum
  )
)

cl_comune$VOTI_SOLO_CANDIDATO <- cl_comune$VOTI_CANDIDATO - cl_comune$VOTI_LISTA

cl_uni <- aggregate(
  cbind(VOTI_CANDIDATO, VOTI_SOLO_CANDIDATO) ~
      CIRCOSCRIZIONE +
      COLLEGIOPLURINOMINALE +
      COLLEGIOUNINOMINALE +
      CL,
  cl_comune,
  sum
)

cl_uni$PERCENTUALE <- cl_uni$VOTI_SOLO_CANDIDATO / cl_uni$VOTI_CANDIDATO

cl_circ <- aggregate(
  cbind(VOTI_CANDIDATO, VOTI_SOLO_CANDIDATO) ~
      CIRCOSCRIZIONE +
      CL,
  cl_comune,
  sum
)

cl_naz <- aggregate(
  cbind(VOTI_CANDIDATO, VOTI_SOLO_CANDIDATO) ~ CL,
  cl_comune,
  sum
)

cl_naz$PERCENTUALE <- cl_naz$VOTI_SOLO_CANDIDATO / cl_naz$VOTI_CANDIDATO

cl_naz <- cl_naz[order(
  cl_naz$VOTI_CANDIDATO,
  decreasing = TRUE
), ]

```

```{r cl_naz}
library(kableExtra)
options(knitr.kable.NA = '')

cl_naz$PERCENTUALE <- formattable::percent(cl_naz$PERCENTUALE, 1)

kbl(
  cl_naz,
  row.names = FALSE,
  col.names = c(
    "Coalizione o lista",
    "Voti totali",
    "Voti al solo candidato",
    "Percentuale sul totale"
  )
) %>%
  kable_minimal() %>%
  column_spec(
    4,
    background = hsv(
      0.3333,
      1,
      .5,
      pmax(0, cl_naz$PERCENTUALE)
    )
  )

```

`