import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const inputPath = resolve(repoRoot, 'web/static/data/v1/politics-static.json');
const outputPath = resolve(repoRoot, 'web/src/lib/scenario/politics-municipalities.generated.ts');

function asciiJson(value) {
  return JSON.stringify(value, null, 2).replace(/[^\x00-\x7f]/g, (character) => {
    const code = character.charCodeAt(0).toString(16).padStart(4, '0');
    return `\\u${code}`;
  });
}

function stringCode(value) {
  return String(value ?? '').trim();
}

const snapshot = JSON.parse(readFileSync(inputPath, 'utf8'));
const rows = (snapshot.data?.municipalities ?? [])
  .map((row) => ({
    CODICE_COMUNE: stringCode(row.CODICE_COMUNE),
    COMUNE: String(row.COMUNE ?? ''),
    CODICE_PROVINCIA: stringCode(row.CODICE_PROVINCIA),
    PROVINCIA: String(row.PROVINCIA ?? ''),
    CODICE_REGIONE: stringCode(row.CODICE_REGIONE),
    REGIONE: String(row.REGIONE ?? '')
  }))
  .sort((left, right) =>
    [left.CODICE_REGIONE, left.CODICE_PROVINCIA, left.COMUNE, left.CODICE_COMUNE]
      .join('\u001f')
      .localeCompare(
        [right.CODICE_REGIONE, right.CODICE_PROVINCIA, right.COMUNE, right.CODICE_COMUNE].join('\u001f'),
        'it'
      )
  );
const tuples = rows.map((row) => [
  row.CODICE_COMUNE,
  row.COMUNE,
  row.CODICE_PROVINCIA,
  row.PROVINCIA,
  row.CODICE_REGIONE,
  row.REGIONE
]);

const content = `// Generated by scripts/export_politics_municipality_catalog.mjs from web/static/data/v1/politics-static.json.
// Do not edit this file by hand.

import type { PoliticsMunicipalityCatalogRow } from '$lib/politics/types';

type MunicipalityCatalogTuple = [string, string, string, string, string, string];

const municipalityRows: MunicipalityCatalogTuple[] = ${asciiJson(tuples)};

export const generatedPoliticsMunicipalities: PoliticsMunicipalityCatalogRow[] = municipalityRows.map(
  ([CODICE_COMUNE, COMUNE, CODICE_PROVINCIA, PROVINCIA, CODICE_REGIONE, REGIONE]) => ({
    CODICE_COMUNE,
    COMUNE,
    CODICE_PROVINCIA,
    PROVINCIA,
    CODICE_REGIONE,
    REGIONE
  })
);
`;

writeFileSync(outputPath, content);
console.log(`Wrote ${outputPath}`);
