import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const inputPath = resolve(repoRoot, 'web/static/data/v1/politics-static.json');
const outputPath = resolve(repoRoot, 'web/src/lib/scenario/politics-candidate-slots.generated.ts');

function asciiJson(value) {
  return JSON.stringify(value, null, 2).replace(/[^\x00-\x7f]/g, (character) => {
    const code = character.charCodeAt(0).toString(16).padStart(4, '0');
    return `\\u${code}`;
  });
}

function stringCode(value) {
  return String(value ?? '').trim();
}

function stringLabel(value) {
  return String(value ?? '').trim();
}

function numeric(value, fallback = 0) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function plurinominalMaxFromScenario(scenarioRows, pluriCode) {
  const code = stringCode(pluriCode);
  const rows = scenarioRows.filter((row) => stringCode(row.PLURI_COD) === code);
  return rows.reduce((max, row) => Math.max(max, numeric(row.NUMERO_CANDIDATO)), 0);
}

function byRamoThenCodes(left, right) {
  return [left[0], left[1], left[3], left[5] ?? '']
    .join('\u001f')
    .localeCompare([right[0], right[1], right[3], right[5] ?? ''].join('\u001f'), 'it', { numeric: true });
}

const snapshot = JSON.parse(readFileSync(inputPath, 'utf8'));
const uninominalRows = [];
const plurinominalRows = [];

for (const ramo of ['camera', 'senato']) {
  const data = snapshot.data?.[ramo] ?? {};
  const scenario = snapshot.default_scenario?.[ramo] ?? {};

  for (const row of data.uni ?? []) {
    const uninominalCode = stringCode(row.UNI_COD);
    if (!uninominalCode) continue;

    uninominalRows.push([
      ramo,
      stringCode(row.CIRC_COD),
      stringLabel(row.CIRC_DEN),
      stringCode(row.PLURI_COD),
      stringLabel(row.PLURI_DEN),
      uninominalCode,
      stringLabel(row.UNI_DEN)
    ]);
  }

  for (const row of data.pluri ?? []) {
    const pluriCode = stringCode(row.PLURI_COD);
    const maxCandidates = Math.max(
      numeric(row.MAX_CANDIDATI),
      plurinominalMaxFromScenario(scenario.candidati_pluri ?? [], row.PLURI_COD)
    );
    if (!pluriCode || maxCandidates <= 0) continue;

    plurinominalRows.push([
      ramo,
      stringCode(row.CIRC_COD),
      stringLabel(row.CIRC_DEN),
      pluriCode,
      stringLabel(row.PLURI_DEN),
      numeric(row.SEGGI_PLURI),
      maxCandidates
    ]);
  }
}

uninominalRows.sort(byRamoThenCodes);
plurinominalRows.sort(byRamoThenCodes);

const content = `// Generated by scripts/export_politics_candidate_slots.mjs from web/static/data/v1/politics-static.json.
// Do not edit this file by hand.

import type { PoliticsCandidateSlotCatalog } from '$lib/scenario/politics-candidate-slots';

type UninominalSlotTuple = [string, string, string, string, string, string, string];
type PlurinominalSlotTuple = [string, string, string, string, string, number, number];

const uninominalRows: UninominalSlotTuple[] = ${asciiJson(uninominalRows)};

const plurinominalRows: PlurinominalSlotTuple[] = ${asciiJson(plurinominalRows)};

export const generatedPoliticsCandidateSlots: PoliticsCandidateSlotCatalog = {
  uninominal: uninominalRows.map(
    ([ramo, circCode, circLabel, pluriCode, pluriLabel, uninominalCode, uninominalLabel]) => ({
      ramo: ramo === 'senato' ? 'senato' : 'camera',
      circCode,
      circLabel,
      pluriCode,
      pluriLabel,
      uninominalCode,
      uninominalLabel
    })
  ),
  plurinominal: plurinominalRows.map(([ramo, circCode, circLabel, pluriCode, pluriLabel, seats, maxCandidates]) => ({
    ramo: ramo === 'senato' ? 'senato' : 'camera',
    circCode,
    circLabel,
    pluriCode,
    pluriLabel,
    seats,
    maxCandidates
  }))
};
`;

writeFileSync(outputPath, content);
console.log(`Wrote ${outputPath}`);
